"""Added MedicalCondition table

Revision ID: 4bf0679e5920
Revises: e09dc1acf911
Create Date: 2025-08-30 02:29:17.644995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf0679e5920'
down_revision: Union[str, Sequence[str], None] = 'e09dc1acf911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_conditions',
    sa.Column('condition_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('condition_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'resolved', name='conditionstatusenum'), nullable=True),
    sa.Column('diagnosed', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doc_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_index(op.f('ix_medical_conditions_condition_id'), 'medical_conditions', ['condition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_conditions_condition_id'), table_name='medical_conditions')
    op.drop_table('medical_conditions')
    # ### end Alembic commands ###
