"""Add height, weight, bmi fields to vitals

Revision ID: 70795320657f
Revises: 50d71df65619
Create Date: 2025-08-31 02:35:37.516268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70795320657f'
down_revision: Union[str, Sequence[str], None] = '50d71df65619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vital_snapshots', sa.Column('height_cm', sa.Float(), nullable=True))
    op.add_column('vital_snapshots', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('vital_snapshots', sa.Column('bmi', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vital_snapshots', 'bmi')
    op.drop_column('vital_snapshots', 'weight_kg')
    op.drop_column('vital_snapshots', 'height_cm')
    # ### end Alembic commands ###
