"""Added Procedures table

Revision ID: b02d113ca3a6
Revises: 4594bc70e326
Create Date: 2025-08-30 04:35:48.640136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b02d113ca3a6'
down_revision: Union[str, Sequence[str], None] = '4594bc70e326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_procedures',
    sa.Column('procedure_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('procedure_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('scheduled', 'completed', 'cancelled', name='procedurestatusenum'), nullable=True),
    sa.Column('performed_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doc_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('procedure_id')
    )
    op.create_index(op.f('ix_medical_procedures_procedure_id'), 'medical_procedures', ['procedure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_procedures_procedure_id'), table_name='medical_procedures')
    op.drop_table('medical_procedures')
    # ### end Alembic commands ###
